# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WWSwift_Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WWSwift_Test

#pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON’, ‘~>4.0’
pod 'Kingfisher', '~>4.6'
pod 'SnapKit', '~> 4.0.0'
pod 'Moya/RxSwift', '~> 11.0'
#pod 'RealmSwift'
pod 'RxCocoa'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh'
pod 'Cache', '~> 4.1.2'
pod 'DeviceKit', '~> 1.4'

end
